//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento_Contable
    {
        public int idAsiento { get; set; }
        public string Descripcion { get; set; }
        public int idTipoInventario { get; set; }
        public string Cuenta_Contable { get; set; }
        public string Tipo_Movimiento { get; set; }
        public System.DateTime Fecha_Asiento { get; set; }
        public decimal Monto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Tipo_Inventario Tipo_Inventario { get; set; }
    }
}
