//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioDBEntities : DbContext
    {
        public InventarioDBEntities()
            : base("name=InventarioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<AlmacenxExistencia> AlmacenxExistencia { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Asiento_Contable> Asiento_Contable { get; set; }
        public virtual DbSet<Tipo_Inventario> Tipo_Inventario { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
    }
}
